version: '3'
services:
  app:
    image: ${DOCKER_IMAGE}
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      PROD_MYSQL_HOST: ${PROD_MYSQL_HOST}
      PROD_MYSQL_DB_NAME: ${PROD_MYSQL_DB_NAME}
      PROD_MYSQL_USERNAME: ${PROD_MYSQL_USERNAME}
      PROD_MYSQL_PASSWORD: ${PROD_MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge