spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${PROD_MYSQL_HOST}:3306/${PROD_MYSQL_DB_NAME}
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver